### ISSUE TITLE
Develop tests to validate the correct functioning of the components of the DataWriterDemo.

### ISSUE THREAD

**Issue by bieryAtFnal** [DUNE-DAQ/ddpdemo#8]

**Comment by carloschavez** [comment]
Just as a summary of what it was done here.  A unittest StoreKey_test was implemented to test for the StorgeKey interface. The test simply checks for the storage of a key and its retrieval is check for correctness. 

I also added KeyedDataBlock_test in order to check for the correct retrieval of the pointer used to hold the address of the datablock in the  KeyedDataBlock class. This did not made it to the V1.0 of the demo code and was left in the issue8_unitTest branch.
